composer.json, src/bundle/Controller/RecommendationController.php, src/lib/Api/AbstractApi.php, src/lib/Api/Recommendation.php, src/lib/Event/Subscriber/RecommendationEventSubscriber.php, src/lib/Event/Subscriber/RecommendationRandomContentEventSubscriber.php, src/lib/Exporter/Exporter.php, src/lib/Request/BasicRecommendationRequest.php, src/lib/Request/EventNotifierRequest.php, src/lib/Request/ExportNotifierRequest.php, src/lib/SPI/RecommendationRequest.php, src/lib/SPI/Request.php, src/lib/Service/RecommendationService.php, src/lib/Service/RecommendationServiceInterface.php, src/lib/Service/SignalSlotService.php, src/lib/Tests/Config/CredentialsCheckerTest.php, src/lib/Tests/Config/ExportCredentialsCheckerTest.php, src/lib/Tests/Config/EzRecommendationClientCredentialsCheckerTest.php, src/lib/Tests/Service/SignalSlotServiceTest.php
https://jira.ez.no/browse/EZEE-2848
=> EZEE-2848: Support for Submodel Request Parameters

src/lib/Content/Content.php
https://jira.ez.no/browse/EZEE-2850
=> EZEE-2850: Invalid uri attribute for exported content items

composer.json, src/lib/Event/Subscriber/RecommendationEventSubscriber.php
https://jira.ez.no/browse/EZEE-2851
=> EZEE-2851: Client sends request only in default language (eng) regardless of current site access / language version

src/bundle/Command/UserAttributesUpdateCommand.php, src/bundle/Resources/config/default_settings.yml, src/bundle/Resources/config/services/commands.yml, src/bundle/Resources/config/services/events.yml, src/lib/Api/AllowedApi.php, src/lib/Api/User.php, src/lib/Client/EzRecommendationClientInterface.php, src/lib/Event/UserAPIEvent.php, src/lib/Request/UserMetadataRequest.php, src/lib/SPI/Request.php, src/lib/SPI/UserAPIRequest.php
https://jira.ez.no/browse/EZEE-2849
=> EZEE-2849: Support for user api endpoint

composer.json, src/bundle/Resources/config/services/events.yml, src/bundle/Serializer/Normalizer/AttributeNormalizer.php, src/bundle/Serializer/Normalizer/UserCollectionNormalizer.php, src/bundle/Serializer/Normalizer/UserNormalizer.php, src/lib/Event/GenerateUserCollectionDataEvent.php, src/lib/Event/Subscriber/UserCollectionGeneratorEventSubscriber.php, src/lib/Value/Output/Attribute.php, src/lib/Value/Output/User.php, src/lib/Value/Output/UserCollection.php
https://jira.ez.no/browse/EZEE-2849
=> EZEE-2849: xml generator

src/bundle/Resources/config/services/events.yml, src/lib/Event/GenerateUserCollectionDataEvent.php, src/lib/Event/Subscriber/UserApiRequestDefaultSourceEventSubscriber.php, src/lib/Event/Subscriber/UserCollectionGeneratorEventSubscriber.php, src/lib/SPI/UserAPIRequest.php
https://jira.ez.no/browse/EZEE-2849
=> EZEE-2849 - Xml Generator improvements

composer.json, src/bundle/DependencyInjection/Configuration.php, src/bundle/Resources/config/default_settings.yaml
Updated composer.json - sf5 support
=> Updated composer.json - sf5 support

src/bundle/Command/ExportCommand.php, src/bundle/Resources/config/services/helpers.yaml, src/lib/Factory/EzRecommendationClientAPIFactory.php, src/lib/Field/Value.php
https://jira.ez.no/browse/EZEE-3140
=> EZEE-3140: Fixed data export

src/lib/Event/Subscriber/RecommendationEventSubscriber.php, src/lib/Helper/LocationHelper.php
Set parent location in recommendation request
=> Set parent location in recommendation request

src/bundle/Resources/config/services/helpers.yml, src/bundle/Resources/config/services/services.yml, src/lib/Field/TypeValue.php, src/lib/Request/EventNotifierRequest.php, src/lib/Service/SignalSlotService.php
This PR provides fixes for content export and content update.
1. Changed request body in content update - added credentials for basic authentication
2. Changed imageVariationService
=> Fixed export and update

src/bundle/Controller/ContentController.php, src/bundle/Controller/ContentTypeController.php, src/bundle/Resources/config/services/exporter.yml, src/lib/Exporter/Exporter.php
Jira issue: https://jira.ez.no/browse/EZP-31959
=> Fixed Explorer being dependant on Anonymous User Permissions

src/lib/Event/Subscriber/TrashEventSubscriber.php, src/lib/Tests/Unit/Event/Subscriber/TrashEventSubscriberTest.php
Sudo is used to have access to trash. Without this rights client will not be able to load content relations.
=> Used sudo to get access to trash

src/lib/Authentication/ExportAuthenticator.php, src/lib/Tests/Authentication/ExportAuthenticatorTest.php, src/lib/Tests/Helper/FileSystemTest.php, src/lib/Value/Config/ExportCredentials.php
https://issues.ibexa.co/browse/EZP-32229
Tests directory has been moved to separate namespace in v2.X
=> EZP-32229: Fixed ExportCredentials for alphanumerical user login

COPYRIGHT, LICENSE, LICENSE-bul, composer.json
| **JIRA issue**                          | [EZEE-3422](https://issues.ibexa.co/browse/EZEE-3422)
| **Type**                                   | improvement
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no
This PR creates or updates LICENSE, LICENSE-bul, COPYRIGHT and README files according to new requirements for Ibexa v3.3 release. ~ATM this PR **changes** GPL license to proprietary one since Personalization is a part of Ibexa DXP BUL.~
=> EZEE-3422: Prepared LICENSE and COPYRIGHT files for 3.3 release

src/bundle/Command/ExportCommand.php, src/bundle/Command/UserAttributesUpdateCommand.php, src/bundle/Resources/config/services/commands.yaml
> JIRA: [EZP-32259](https://jira.ez.no/browse/EZP-32259)
Replaced "ezplatform" commands namespace with "ibexa".
<table><tbody><tr><td>Old name</td><td>New name</td></tr><tr><td><code>ezrecommendation:export:run</code></td><td><code>ibexa:recommendation:run-export</code></td></tr><tr><td><code>ezrecommendation:user:update</code></td><td><code>ibexa:recommendation:update-user</code></td></tr></tbody></table>
Requires ezsystems/ezplatform-kernel#153.
*   [x] Code follows the code style of this project (use `$ composer fix-cs`).
*   [x] Change requires a change to the documentation.
*   [x] Code is ready for a review.
=> EZP-32259: Replaced "ezplatform" commands namespace with "ibexa"

.github/pull_request_template.md, .github/workflows/ci.yml, composer.json, phpstan-baseline.neon, phpstan.neon, src/bundle/DependencyInjection/Configuration.php
This PR adds Github Actions similar to the ones present in other repositories.
- Code style checks
- Maximum level of PHPStan strictness.
=> Added Github Actions / PHPStan / Code Style checks

.github/pull_request_template.md, .github/workflows/ci.yml, .travis.yml, composer.json
| **JIRA issue**                          | -
| **Type**                                   | improvement
| **Target Ibexa DXP version** | `v4.0`
| **BC breaks**                          | no
| **Doc needed**                       | no
This PR changes:
- PHP version 
- Target Ibexa DXP version in PR template
=> Bumped PHP version to 7.4

src/contracts/Value/ItemListInterface.php, src/lib/Exception/ItemNotFoundException.php, src/lib/Exception/NotFoundException.php
| **Target Ibexa DXP version** | `v4.0.0`
This PR provides added ItemListInterface which will represent the collection of fetched items. 
There are also added three basic methods. Next methods will be added in next steps. 
In case when item will be not found on the list ItemNotFoundException should be thrown.
=> Added item list contract

src/contracts/Value/ItemListInterface.php
| **Target Ibexa DXP version** | `v4.0.0` 
Added method to slice item list
=> IBX-607: Added slice method to ItemListInterface

src/contracts/Value/ItemGroupInterface.php, src/contracts/Value/ItemGroupListInterface.php, tests/lib/Stubs/ItemGroup.php, tests/lib/Stubs/ItemGroupList.php
| **JIRA issue**                          | [IBX-607](https://issues.ibexa.co/browse/IBX-607)
| **Type**                                   | feature
| **Target Ibexa DXP version** | `v4.0.0` 
Added contracts needed to creating group of items.
=> IBX-607: Added ItemGroup and ItemGroupList contracts

.github/workflows/ci.yml, composer.json, phpstan-baseline.neon
| **JIRA issue**                          | [IBX-596](https://issues.ibexa.co/browse/IBX-596)
| **Type**                                   | feature/bug/improvement
| **Target Ibexa DXP version** | `v4.x` - please update `x` accordingly
| **BC breaks**                          | yes/no
| **Doc needed**                       | yes/no
=> IBX-596: As a QA I want to change php-cs occurrences into check-cs for consistency

composer.json, phpunit.xml, tests/integration/IbexaKernelTestCase.php, tests/integration/IbexaTestKernel.php
| **JIRA issue**                          | [IBX-765](https://issues.ibexa.co/browse/IBX-765)
| **Type**                                   | feature
| **Target Ibexa DXP version** | `v4.0.0`
| **BC breaks**                          | no
| **Doc needed**                       | no
This PR provides configured test kernel for integration tests
=> IBX-765: Added test kernel for integration tests

src/bundle/Resources/config/services.yaml, src/bundle/Resources/config/services/export.yaml, src/lib/Export/Input/CommandInputResolver.php, src/lib/Export/Input/CommandInputResolverInterface.php, tests/lib/Export/Input/CommandInputResolverTest.php
Following: https://github.com/ezsystems/ezrecommendation-client/pull/67
This PR provides resolver which takes command input parameters and replaces "-" to "_"
=> IBX-201: Added CommandInputResolver

src/bundle/Resources/config/services/helpers.yaml, src/lib/Exporter/Exporter.php, src/lib/Exporter/ExporterInterface.php, src/lib/Helper/ContentHelper.php, src/lib/Helper/SiteAccessHelper.php, src/lib/Service/ExportNotificationService.php, src/lib/Service/ExportService.php, src/lib/Service/ExportServiceInterface.php, src/lib/Service/Notification/NotificationServiceInterface.php, tests/lib/Helper/SiteAccessHelperTest.php, tests/lib/Service/ExportNotificationServiceTest.php
Following: https://github.com/ezsystems/ezrecommendation-client/pull/67
This PR provides fixes after `CommandExport`, `ExportParametersFactory` refactoring to keep export working. 
In next steps `Exporter`, `NotificationService` etc will be refactored.
=> IBX-201:Fixes after refactoring

composer.json, src/bundle/Resources/config/services/services.yaml, src/lib/Criteria/Criteria.php, src/lib/Service/Storage/DataSourceService.php, src/lib/Service/Storage/DataSourceServiceInterface.php, src/lib/Storage/ContentDataSource.php, src/lib/Strategy/Storage/GroupByItemTypeAndLanguageStrategy.php, src/lib/Strategy/Storage/SupportedGroupItemStrategy.php, src/lib/Value/Storage/Item.php, src/lib/Value/Storage/ItemGroup.php, src/lib/Value/Storage/ItemGroupList.php, src/lib/Value/Storage/ItemList.php, src/lib/Value/Storage/ItemType.php, tests/lib/Creator/DataSourceTestItemCreator.php, tests/lib/Export/Input/CommandInputResolverTest.php, tests/lib/Factory/Export/ParametersFactoryTest.php, tests/lib/Service/Storage/DataSourceServiceTest.php, tests/lib/Storage/AbstractDataSourceTestCase.php, tests/lib/Storage/AbstractItemTestCase.php, tests/lib/Storage/InMemoryDataSourceTest.php, tests/lib/Strategy/Storage/GroupByItemTypeAndLanguageStrategyTest.php, tests/lib/Strategy/Storage/GroupItemStrategyDispatcherTest.php
| **Target Ibexa DXP version** | `v4.0.0` 
| **BC breaks**                          | no
| **Doc needed**                       | no
This PR provides moved new classes (mostly related to data source implementation) to Ibexa\Personalization namespace.
=> Moved new classes to Ibexa\Personalization namespace
